stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  VENV_PATH: ".venv"

cache:
  paths:
    - .venv/

before_script:
  - python3 -m venv $VENV_PATH
  - source $VENV_PATH/bin/activate
  - pip install -U pip build twine

test:
  tags:
    - shell
  stage: test
  script:
    - pip install .[test]
    - pytest --junitxml=reports/rspec.xml
  artifacts:
    when: always
    paths:
      - reports/rspec.xml
    reports:
      junit: reports/rspec.xml

build_package:
  tags:
    - shell
  stage: build
  script:
    - rm -rf dist/
    - python -m build
  artifacts:
    paths:
      - dist/*.tar.gz
      - dist/*.whl

publish_pypi:
  tags:
    - shell
  stage: deploy
  needs: ["build_package"]
  script:
    - twine upload -u __token__ -P "$TOKEN" --repository-url "$TARGET_REPOSITORY" dist/*
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG'
      VARIABLES:
        TOKEN: "$PYPI_TOKEN"
        TARGET_REPOSITORY: "https://upload.pypi.org/legacy/"
      when: always
    - if: '$CI_COMMIT_BRANCH == "dev"'
      VARIABLES:
        TOKEN: "$PYPI_TEST_TOKEN"
        TARGET_REPOSITORY: "https://test.pypi.org/legacy/"
      when: always
    - when: never

docker_build_push:
  tags:
    - docker
  stage: deploy
  needs: ["build_package"]
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  variables:
    DOCKER_BUILDKIT: 1
  before_script:
    - echo "$REGISTRY_TOKEN" | docker login -u "$REGISTRY_USER" --password-stdin "$REGISTRY"
  script:
    - docker buildx build --push --tag $IMAGE_TAG_LATEST --tag $IMAGE_TAG_COMMIT -f docker/Dockerfile .
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG'
      variables:
        REGISTRY: "$DOCKER_REGISTRY"
        REGISTRY_USER: "$DOCKER_REGISTRY_USER"
        REGISTRY_TOKEN: "$DOCKER_REGISTRY_TOKEN"
        IMAGE_TAG_LATEST: "$DOCKER_REGISTRY:latest"
        IMAGE_TAG_COMMIT: "$DOCKER_REGISTRY:$CI_COMMIT_SHORT_SHA"
      when: always
    - if: '$CI_COMMIT_BRANCH == "dev"'
      variables:
        REGISTRY: "$CI_REGISTRY"
        REGISTRY_USER: "$CI_REGISTRY_USER"
        REGISTRY_TOKEN: "$CI_REGISTRY_PASSWORD"
        IMAGE_TAG_LATEST: "$CI_REGISTRY_IMAGE:latest"
        IMAGE_TAG_COMMIT: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
      when: always
    - when: never
