version: "3"
services:
  pterodactyl-exporter:
    image: loens2/pterodactyl_exporter:latest
    container_name: pterodactyl-exporter
    ports:
      - "9531:9531"
    volumes:
      - ../enum.yml:/opt/pterodactyl_exporter/enum/enum.yml
